# Generated by Django 4.1.1 on 2023-02-03 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200, unique=True)),
                ('sales_price', models.FloatField(max_length=200)),
                ('purchase_price', models.FloatField(max_length=200, null=True)),
            ],
        ),
    ]
