# Generated by Django 4.1.1 on 2023-02-04 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='purchase_price',
            field=models.FloatField(blank=True, default=0, max_length=200, null=True),
        ),
    ]
